### ISSUE TITLE
Doesn't work with the new Auto theme setting in macOS Catalina

### ISSUE THREAD

**Issue by jtovar43** [LinusU/vscode-auto-dark-mode#11]
I'm running the latest beta of macOS Catalina and the extension still works if you manually change the theme from light to dark. But the extension doesn't seem to work with the new Auto theme that this update brings which switches the OS from light to dark or visa versa based off sunrise and sunset.

**Comment by muhelen** [comment]
Yes, its not working with Catalina public release too.

**Comment by cprecioso** [comment]
This has already been reported in the helper tool repository: https://github.com/LinusU/DarkModeListener/issues/1

**Comment by Nataniel4** [comment]
This feature appears to be supported natively by vscode 🤔 
```json
"window.autoDetectColorScheme": true,
"workbench.preferredLightColorTheme": "Default Light+",
"workbench.preferredDarkColorTheme": "Default Dark+"
```

**Comment by michaelgosling** [comment]
That’s a new vscode feature!

**Comment by jtovar43** [comment]
Yeah I noticed that the other day too. Glad they finally included it as a feature.

**Comment by LinusU** [comment]
That's amazing, I'll add a notice to the readme and then we can deprecate this package ☺️

**Comment by ChrisChinchilla** [comment]
Wow they snuck that in!
