### ISSUE TITLE
What do we need to make this work with Windows?

### ISSUE THREAD

**Issue by brunofin** [LinusU/vscode-auto-dark-mode#14]
I could dedicate some of my time to try to implement what is needed to make this work on Windows as well, I just want to know if there are any technical limitations on why this extension doesn't support it or if it simply wasn't implemented.

**Comment by brunofin** [comment]
Sorry, I realized I didn't even test the extension before creating this issue.
The description says it works only on macOS but it works perfectly fine on Windows too.

I am closing this.

Side note: does it work with Linux though? ;)

**Comment by LinusU** [comment]
fixed the documentation here c861fe0
