### ISSUE TITLE
Theme: One Dark+(Sublime) not support on newest vscode version

### ISSUE THREAD

**Issue by hl-lab** [LinusU/vscode-auto-dark-mode#2]
recently, theme: One Dark+(Sublime) can't be auto changed.
it's not happend before, i think the problem mybe occured by new vscode version.

please fixed it. tks

**Comment by LinusU** [comment]
Hey, sorry for not getting back to you earlier. What, if any, error are you getting? Does it work if you manually put the same string into your `settings.json` file?

**Comment by LinusU** [comment]
Feel free to reopen if you still have a problem :)

**Comment by hl-lab** [comment]
> Hey, sorry for not getting back to you earlier. What, if any, error are you getting? Does it work if you manually put the same string into your `settings.json` file?

yeah, I input string in `settings.json` file it works!  seems space character make it failure.
theme real name is : One Dark+ (Sublime)
