### ISSUE TITLE
Documentation: How to setup?

### ISSUE THREAD

**Issue by DannyDannyDanny** [LinusU/vscode-auto-dark-mode#21]
Vscode extension newbie here. I've added the extension's exposed fields to my settings.json:

```
{
    "workbench.colorTheme": "Solarized Light",
    "git.autofetch": true,
    "extensions.ignoreRecommendations": true,
     ...
    "autoDarkMode.lightTheme": "Solarized Light",
    "autoDarkMode.darkTheme": "Solarized Dark"
}
```

* What am I missing?
* Suggestion: include a sentence about where these fields can be set
* Suggestion: include a sentence about possible values for these fields

**Comment by LinusU** [comment]
As indicated in the readme, this is supported natively in VS Code now and I would recommend using that instead:

https://code.visualstudio.com/updates/v1_42#_auto-switch-theme-based-on-os-color-scheme

**Comment by DannyDannyDanny** [comment]
My bad, cheers!
