### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by ackvf** [LinusU/vscode-auto-dark-mode#3]
I have troubles making this work on Windows 10, so while I fiddled with the configuration, I discovered few problems:

1) typo `if on` should be `is on`
```diff
- Specifies which theme is to be shown when dark mode if on.
+ Specifies which theme is to be shown when dark mode is on.
```

2) the description on npm and github should mention the two settings. _(I mainly use JSON configuration instead of the new settings and it was a challenge figuring those out at first.)_
```
"autoDarkMode.darkTheme": "Default Dark+"
"autoDarkMode.lightTheme": "Default Light+"
```

3) The default values are "Default Dark+" and "Default Light+", however, I don't see any theme with that name, so I wonder how does it work and what exactly should I type there?
![image](https://user-images.githubusercontent.com/2313018/55611999-73696800-5787-11e9-9cf8-66d1f93e27b2.png)
For example: For the Dark + theme, shouldn't it be "Dark+ (default dark)" instead of "Default Dark+"? OR what is really the name of the theme? I tried all possible combinations to no avail.

4) It would be great if instead of typing the name of theme there is a dropdown with all available themes. (if that's possible to implement)

5) The description should mention supported systems. I don't even know if all my problems aren't simply caused by the fact, that windows 10 might not even be supported. 😭 

Thanks for your time and for developing this extension though!

**Comment by LinusU** [comment]
Thanks for the extensive feedback!

1. 23adb45167bd4f9e0e56e6ea70a23d8e816817ed
2. bf355349e4255a215b92421338db8e95a362ccea
3. It seems that this is what's supposed to be in the config 🤔 

    ![Screenshot 2019-04-11 at 12 16 28](https://user-images.githubusercontent.com/189580/55953450-086ed400-5c54-11e9-8d79-fd39fe8bf670.png)

4. Would love this as well, but haven't looked into it closely, PRs welcome!
5. 25642f74373d6c8f0dcbf9f64fb0ee460ce38948, only macOS is supported right now 🙈

**Comment by ackvf** [comment]
Thanks for the response and for the work :) too bad Windows isn't compatible :( 
Good hint with the `"workbench.colorTheme"! 👍 

Keep up the good work anyway, good luck!
