### ISSUE TITLE
Not supported on latest version (1.27.1)

### ISSUE THREAD

**Issue by andrewmccullough** [LinusU/vscode-auto-dark-mode#6]

**Comment by LinusU** [comment]
It works for me on 1.33.1, could you try updating your version of Visual Studio Code?

**Comment by MarkCalvert** [comment]
I am on the latest mac version 1.27.2 and it will not install either

**Comment by LinusU** [comment]
I'm on mac as well and the latest VS Code version is 1.33.1.

Could it be that something has gone wrong with the auto-updating of your installation? Have you tried selecting "Code" -> "Check for updates..."?

**Comment by MarkCalvert** [comment]
Yes I tried check for updates and it said it was up to date. So I went and manually downloaded version 1.33.1 and the extension install and works now.

**Comment by LinusU** [comment]
Great, closing this then since upgrading VS Code solves it 👍
