### ISSUE TITLE
Doesn't work properly with Remote SSH mode

### ISSUE THREAD

**Issue by 3rock618** [LinusU/vscode-auto-dark-mode#7]
I'm using the [new Remote SSH](https://code.visualstudio.com/docs/remote/ssh) feature, and the extension will only let me install on the SSH remote machine, and not locally.
To reproduce:
- Install VS Code Insiders Build
- Install Remote SSH
- Log in to an SSH remote machine
- Try installing extension (install on local, not available)

**Comment by LinusU** [comment]
Hmm, not really sure how to solve this but would love a PR or just some pointers on how to do it 😄

**Comment by 3rock618** [comment]
I've been using remote SSH a lot and reading up about it. As far as I understand, MS is aware of this problem for it's entire extension framework. Because Remote SSH is such a major update - major parts of VS Code work from a remote machine and do most of the backend compute work, while the UX lives on local - I think they are fixing a lot of these issues on the vscode internals i.e. figuring out which extension functions will be with the UX vs compute sides. Therefore maybe nothing to worry about until Remote SSH hits the main release, as MS is ironing out a lot of issues with the Remote framework right now.

Also thanks for your work. 🙏🏼. I use the ext. daily.

**Comment by devavret** [comment]
+1
Came here to report the same issue. Also, thanks for the extension.

**Comment by tm1000** [comment]
Heres the way to fix it on the extension and also how to set a workaround locally: https://github.com/PsykoSoldi3r/vscode-itunes/issues/17

In a nutshell just add this to your settings.json
```
    "remote.extensionKind": {
        "linusu.auto-dark-mode": "ui"
    },
```

As for the development side you just need to define the extensionKind (I submitted PR #9 to address this)
