### ISSUE TITLE
Intermittent behaviour with macOS mode switching

### ISSUE THREAD

**Issue by SimonBrazell** [LinusU/vscode-auto-dark-mode#8]
Hi love the concept behind this one and really appreciate the effort that has gone into this extension, it really should be something that vscode supports natively (maybe soon?). 

However, this extension seems to work intermittently for me, with the behaviour displayed on each mode change not being consistent. For instance sometimes when I switch the OS mode this extension will not work at all, requiring me to disable and enable it before it does switch the themes, and other times it does work but sets the wrong theme, switching to the default dark mode theme for instance rather than the one I have set in the `settings.json` file, this happened to me just now and I had to switch back again to get it to use my specified theme for dark mode.

Environment:

- Auto Dark Mode 0.1.5
- macOS Mojave 10.14.5
- VS Code 1.35.1

Let me know if there is anything else I can supply to help with this.

**Comment by LinusU** [comment]
I'm sorry it's not working great for you. To be honest, I'm not really sure how to debug this. It would probably help to have some form of logging so need to check if there is a good way to produce logs from extensions 🤔

**Comment by SimonBrazell** [comment]
Thanks @LinusU, it may just happen when my laptop resumes from sleep, need to confirm though. Still super handy when it does work though :-)

**Comment by SimonBrazell** [comment]
Haven't seen this occur on my machine lately, perhaps it was just because I was still fiddling with the settings at the time, hard to say but the extension is working as intended now.
